title: Amanda Egega Domeru
logo: /assets/img/headshot_circle.png
description: Motivated entry-level data analyst with strong analytical, programming, and teamwork skills, passionate about using data to solve problems and drive business growth. 
theme: jekyll-theme-minimal
