title: Amanda Egega Domeru
logo: /assets/img/headshot_circle.png
description: Entry-level data analyst with strong analytical and programming skills, passionate about using data to drive results. 
theme: jekyll-theme-minimal
